name: 'Setup Maven for the action'
description: 'Bump the Maven version (stored in properties.revision) and push it on the repo'

inputs:
  version_type:
    description: 'Type of version bump (major, minor, patch)'
    required: true
    type: string
  TOKEN:
    description: "The git hub token to push the bumped version"
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Validate version_type input
      shell: bash
      run: |
        if [[ "${{ inputs.version_type }}" != "major" && "${{ inputs.version_type }}" != "minor" && "${{ inputs.version_type }}" != "patch" ]]; then
          echo "Invalid version_type: '${{ inputs.version_type }}'. Must be 'major', 'minor', or 'patch'."
          exit 1
        fi
    - name: GIT config
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Bump version in properties.revision
      shell: bash
      run: |
        # Extract current revision version
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout | sed 's/-SNAPSHOT//g') 
        
        # Split the version into major, minor, and patch components
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

        # Increment the appropriate component based on the input version_type
        case ${{ inputs.version_type }} in
          major)
            export NEW_VERSION=$((MAJOR+1)).0.0
            ;;
          minor)
            export NEW_VERSION=$MAJOR.$((MINOR+1)).0
            ;;
          patch)
            export NEW_VERSION=$MAJOR.$MINOR.$((PATCH+1))
            ;;
        esac
        
        echo $NEW_VERSION > .env

        # Update the version in the pom.xml's properties.revision
        mvn versions:set-property -Dproperty=revision -DnewVersion=$NEW_VERSION-SNAPSHOT
        mvn versions:commit
    - name: Push version bump commit
      shell: bash
      run: |
        source .env
        
        BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        git add pom.xml
        git commit -m "Bumped revision version to $NEW_VERSION"
        git tag -a v$NEW_VERSION -m "$NEW_VERSION"
        git push --tags https://${{ inputs.TOKEN }}@github.com/${{ github.repository }} $BRANCH
