name: 'Setup node for the action'
description: 'Setup node for the workflow'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 20 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        architecture: x64
        cache: maven
