spring:
    profiles:
        active: "${ACTIVE_PROFILES}"

logging:
    level:
        org:
            springframework: INFO
            hibernate: WARN
        com.glassait.tanks-and-equipments: DEBUG

server:
    port: 8080