spring:
    application:
        name: "tanks-and-equipment-backend"
    profiles:
        active: "${ACTIVE_PROFILES}"

debug: ${DEBUG}

logging:
    level:
        org:
            springframework: ${LOG_LEVEL_SPRING}
            hibernate: ${LOG_LEVEL_HIBERNATE}
        com.glassait.tanks_and_equipments: ${LOG_LEVEL_ROOT}

server:
    port: 8080