spring:
    application:
        name: "FOLD_ BACKEND"
    profiles:
        active: "${ACTIVE_PROFILES}"

debug: ${DEBUG}

logging:
    level:
        org:
            springframework: INFO
            hibernate: WARN
        com.glassait.tanks_and_equipments: ${LOG_LEVEL_ROOT}

server:
    port: 8080