create table fields
(
    id             int unsigned auto_increment
        primary key,
    tank_id        int unsigned  not null,
    level          int           null,
    `left-name`    varchar(255)  null,
    `left-image`   varchar(255)  null,
    `left-active`  int default 0 null,
    `right-name`   varchar(255)  null,
    `right-image`  varchar(255)  null,
    `right-active` int default 0 null,
    constraint fields_tanks_id_fk
        foreign key (tank_id) references tanks (id)
            on update cascade
);

INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (1, 1, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (2, 1, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (3, 1, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (4, 1, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (5, 1, 7, 'Recâblage de l\'alimentation électrique (Réglage 1)', 'improvedSpeedIndicator', 1, 'Recâblage de l\'alimentation électrique (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (6, 1, 8, 'Plateforme renforcée', 'increasedThickness', 1, 'Plateform légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (7, 2, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (8, 2, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (9, 2, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (10, 2, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (11, 2, 7, 'Recâblage de l\'alimentation électrique (Réglage 1)', 'improvedSpeedIndicator', 1, 'Recâblage de l\'alimentation électrique (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (12, 2, 8, 'Plateforme renforcée', 'increasedThickness', 1, 'Plateform légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (13, 3, 2, 'Augmentation de la durabilité de l\'élément', 'increasedThickness', 1, 'Points de fixation en alliage léger', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (14, 3, 4, 'Ajustement du bras de suspension', 'improvedChassisStability', 0, 'Vision améliorée', 'improvedScope', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (15, 3, 5, 'Ajustement du Turbocompresseur', 'improvedSpeedIndicatorBackwards', 0, 'Phares antireflets', 'improvedLightFilters', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (16, 3, 6, 'Reconnaissance', 'stealth', 0, 'Capacité de survie', 'survivability', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (17, 3, 7, 'Renforcement accru de la durabilité', 'increasedThickness', 1, 'Amélioration accrue de la visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (18, 3, 8, 'Appareils d\'observation supplémentaires', 'improvedObservationDevice', 0, 'Joints renforcés', 'improvedEnginePower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (19, 4, 2, 'Augmentation de la durabilité de l\'élément', 'increasedThickness', 1, 'Points de fixation en alliage léger', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (20, 4, 4, 'Ajustement du bras de suspension', 'improvedChassisStability', 0, 'Vision améliorée', 'improvedScope', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (21, 4, 5, 'Ajustement du Turbocompresseur', 'improvedSpeedIndicatorBackwards', 0, 'Phares antireflets', 'improvedLightFilters', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (22, 4, 6, 'Reconnaissance', 'stealth', 0, 'Capacité de survie', 'survivability', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (23, 4, 7, 'Renforcement accru de la durabilité', 'increasedThickness', 1, 'Amélioration accrue de la visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (24, 4, 8, 'Appareils d\'observation supplémentaires', 'improvedObservationDevice', 0, 'Joints renforcés', 'improvedEnginePower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (25, 5, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (26, 5, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (27, 5, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (28, 5, 6, 'Mobilité', 'mobility', 1, 'Puissance de feu', 'firepower', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (29, 5, 7, 'Ajustement de la puissance de sortie (Réglage 1)', 'improvedSpeedIndicatorBackwards', 1, 'Ajustement de la puissance de sortie (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (30, 5, 8, 'Caisse renforcée', 'improvedSpallingResistance', 0, 'Caisse légère', 'improvedChassisStability', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (31, 6, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (32, 6, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (33, 6, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (34, 6, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (35, 6, 7, 'Ajustement de la puissance de sortie (Réglage 1)', 'improvedSpeedIndicatorBackwards', 1, 'Ajustement de la puissance de sortie (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (36, 6, 8, 'Caisse renforcée', 'improvedSpallingResistance', 1, 'Caisse légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (37, 7, 2, 'Augmentation de la durabilité de l\'élément', 'increasedThickness', 1, 'Points de fixation en alliage léger', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (38, 7, 4, 'Ajustement du bras de suspension', 'improvedChassisStability', 0, 'Vision améliorée', 'improvedScope', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (39, 7, 5, 'Ajustement du Turbocompresseur', 'improvedSpeedIndicatorBackwards', 1, 'Phares antireflets', 'improvedLightFilters', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (40, 7, 6, 'Reconnaissance', 'stealth', 0, 'Capacité de survie', 'survivability', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (41, 7, 7, 'Ajustement du mécanisme de chargement', 'improvedGunBreech', 1, 'Ajustement du mécanisme de visée', 'improvedScope', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (42, 7, 8, 'Ajustement de l\'OPV', 'improvedEnginePower', 0, 'Systéme de visée électrique', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (43, 8, 2, 'Suspension renforcée', 'improvedChassisStability', 0, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (44, 8, 4, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0, 'Ajustement parallaxe', 'improvedScope', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (45, 8, 5, 'Ajustement de l\'éjecteur', 'improvedMuzzleBreak', 1, 'Périscope à angle droit', 'improvedObservationDevice', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (46, 8, 6, 'Reconnaissance', 'stealth', 0, 'Capacité de survie', 'survivability', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (47, 8, 7, 'Systéme de sécurité passif', 'increasedThickness', 1, 'Reconfiguration du râtelier à munitions', 'improvedGunBreech', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (48, 8, 8, 'Chenilles réparables', 'improvedSelfRepairingTracks', 0, 'Ajustement du compartiment moteur', 'improvedSpeedIndicatorBackwards', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (49, 9, 2, 'Ajustement des valves (Réglage 1)', 'improvedEnginePower', 0, 'Ajustement des valves (Réglage 2)', 'betterFriction', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (50, 9, 4, 'Ajustement du mécanisme de chargement', 'improvedGunBreech', 1, 'Ajustement du mécanisme de visée', 'improvedScope', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (51, 9, 5, 'Protection anti-éclats renforcée', 'improvedSpallingResistance', 1, 'Protection anti-éclats légère', 'improvedSpeedIndicatorBackwards', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (52, 9, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (53, 9, 7, 'Structure principale renforcée', 'reinforcedStructure', 0, 'Agrandissement du compartiment de la tourelle', 'improvedGunBreech', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (54, 9, 8, 'Kit de reconnaissance', 'increasedSensitivityOptics', 0, 'Kit de l\'assaillant', 'improvedSelfRepairingWheels', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (55, 10, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (56, 10, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (57, 10, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (58, 10, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (59, 10, 7, 'Recâblage de l\'alimentation électrique (Réglage 1)', 'improvedSpeedIndicator', 1, 'Recâblage de l\'alimentation électrique (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (60, 10, 8, 'Plateforme renforcée', 'increasedThickness', 1, 'Plateform légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (61, 11, 2, 'Suspension renforcée', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (62, 11, 4, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0, 'Ajustement parallaxe', 'improvedScope', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (63, 11, 5, 'Ajustement de l\'éjecteur', 'improvedMuzzleBreak', 0, 'Périscope à angle droit', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (64, 11, 6, 'Reconnaissance', 'stealth', 0, 'Capacité de survie', 'survivability', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (65, 11, 7, 'Systéme de sécurité passif', 'increasedThickness', 1, 'Reconfiguration du râtelier à munitions', 'improvedGunBreech', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (66, 11, 8, 'Chenilles réparables', 'improvedSelfRepairingTracks', 1, 'Ajustement du compartiment moteur', 'improvedSpeedIndicatorBackwards', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (67, 12, 2, 'Augmentation de la durabilité de l\'élément', 'increasedThickness', 1, 'Points de fixation en alliage léger', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (68, 12, 4, 'Ajustement du bras de suspension', 'improvedChassisStability', 0, 'Vision améliorée', 'improvedScope', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (69, 12, 5, 'Ajustement du Turbocompresseur', 'improvedSpeedIndicatorBackwards', 1, 'Phares antireflets', 'improvedLightFilters', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (70, 12, 6, 'Reconnaissance', 'stealth', 0, 'Capacité de survie', 'survivability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (71, 12, 7, 'Ajustement du mécanisme de chargement', 'improvedGunBreech', 0, 'Ajustement du mécanisme de visée', 'improvedScope', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (72, 12, 8, 'Ajustement de l\'OPV', 'improvedEnginePower', 0, 'Systéme de visée électrique', 'improvedAimingHandling', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (73, 13, 2, 'Suspension renforcée', 'improvedChassisStability', 0, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (74, 13, 4, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0, 'Ajustement parallaxe', 'improvedScope', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (75, 13, 5, 'Ajustement de l\'éjecteur', 'improvedMuzzleBreak', 1, 'Périscope à angle droit', 'improvedObservationDevice', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (76, 13, 6, 'Reconnaissance', 'stealth', 1, 'Capacité de survie', 'survivability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (77, 13, 7, 'Ajustement du mécanisme de chargement', 'improvedGunBreech', 0, 'Ajustement du mécanisme de visée', 'improvedScope', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (78, 13, 8, 'Ajustement de l\'OPV', 'improvedEnginePower', 0, 'Systéme de visée électrique', 'improvedAimingHandling', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (79, 14, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (80, 14, 4, 'Ajustement parallaxe', 'improvedScope', 0, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (81, 14, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (82, 14, 6, 'Mobilité', 'mobility', 1, 'Puissance de feu', 'firepower', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (83, 14, 7, 'Recâblage de l\'alimentation électrique (Réglage 1)', 'improvedSpeedIndicator', 1, 'Recâblage de l\'alimentation électrique (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (84, 14, 8, 'Plateforme renforcée', 'increasedThickness', 0, 'Plateform légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (85, 15, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (86, 15, 4, 'Ajustement parallaxe', 'improvedScope', 0, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (87, 15, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (88, 15, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (89, 15, 7, 'Ajustement de la puissance de sortie (Réglage 1)', 'improvedSpeedIndicatorBackwards', 1, 'Ajustement de la puissance de sortie (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (90, 15, 8, 'Caisse renforcée', 'improvedSpallingResistance', 1, 'Caisse légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (91, 16, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (92, 16, 4, 'Ajustement parallaxe', 'improvedScope', 0, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (93, 16, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (94, 16, 6, 'Mobilité', 'mobility', 1, 'Puissance de feu', 'firepower', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (95, 16, 7, 'Mobilité avant tout', 'improvedSpeedIndicatorBackwards', 0, 'Puissance de feu avant tout', 'improvedGunBreech', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (96, 16, 8, 'Canon lourd', 'increasedThickness', 1, 'Canon léger', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (97, 17, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (98, 17, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (99, 17, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (100, 17, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (101, 17, 7, 'Recâblage de l\'alimentation électrique (Réglage 1)', 'improvedSpeedIndicator', 1, 'Recâblage de l\'alimentation électrique (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (102, 17, 8, 'Plateforme renforcée', 'increasedThickness', 1, 'Plateform légère', 'improvedChassisStability', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (103, 18, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (104, 18, 4, 'Ajustement parallaxe', 'improvedScope', 0, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (105, 18, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (106, 18, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (107, 18, 7, 'Isolation du bruit supplémentaire', 'improvedSpallingResistance', 0, 'Retrait du capitonnage', 'improvedSpeedIndicator', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (108, 18, 8, 'Système de sécurité secondaire', 'reinforcedInteriorModules', 1, 'Points de fixation légers', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (109, 19, 2, 'Suspension tout-terrain', 'additionalGrousers', 1, 'Suspension légère', 'betterFriction', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (110, 19, 4, 'Ajustement parallaxe', 'improvedScope', 1, 'Rodage des mécanismes de visée', 'improvedAimingHandling', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (111, 19, 5, 'Isolation sonore', 'improvedSpallingResistance', 0, 'Motorisation électrique du périscope', 'improvedObservationDevice', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (112, 19, 6, 'Mobilité', 'mobility', 0, 'Puissance de feu', 'firepower', 1);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (113, 19, 7, 'Ajustement de la puissance de sortie (Réglage 1)', 'improvedSpeedIndicatorBackwards', 1, 'Ajustement de la puissance de sortie (Réglage 2)', 'improvedTurretTurningWheels', 0);
INSERT INTO fields (id, tank_id, level, `left-name`, `left-image`, `left-active`, `right-name`, `right-image`, `right-active`) VALUES (114, 19, 8, 'Caisse renforcée', 'improvedSpallingResistance', 1, 'Caisse légère', 'improvedChassisStability', 0);
